//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryproject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BookTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookTable()
        {
            this.BookFineTables = new HashSet<BookFineTable>();
            this.BookReturnTables = new HashSet<BookReturnTable>();
            this.IssueBookTables = new HashSet<IssueBookTable>();
        }
    
        public int BookID { get; set; }
        public int DepartmentID { get; set; }
        public int BookTypeID { get; set; }
        [Required(ErrorMessage = "Please enter Book Titile"), MaxLength(30)]
        public string BookTitle { get; set; }
        [Required(ErrorMessage = "Please enter Author Name"), MaxLength(30)]
        public string Author { get; set; }
        [Required(ErrorMessage = "Please enter Book Name"), MaxLength(30)]
        public string BookName { get; set; }
        [Required(ErrorMessage = "Please enter Edition")]
        [Range(1,50, ErrorMessage = "Please enter valid Edition")]

        public double Edition { get; set; }
        [Required(ErrorMessage = "Please enter Total Copies")]
        [Range(1,30, ErrorMessage = "Please enter valid number of Copies")]
        public int TotalCopies { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime RegDate { get; set; }
        [Required(ErrorMessage = "Please enter price")]
        [Range(100,40000, ErrorMessage = "Please enter valid Edition")]
        public double Price { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookFineTable> BookFineTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookReturnTable> BookReturnTables { get; set; }
        public virtual BookTypeTable BookTypeTable { get; set; }
        public virtual DepartmentTable DepartmentTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueBookTable> IssueBookTables { get; set; }
    }
}
