//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryproject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class BookReturnTable
    {
        public int BookReturnID { get; set; }
        public int BookID { get; set; }
        public int StudentID { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime IssueDate { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime ReturnDate { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime CurrentDate { get; set; }
    
        public virtual BookTable BookTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
