//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryproject
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class BookFineTable
    {
        public int BookFineID { get; set; }
        public int BookID { get; set; }
        public int StudentID { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime FineDate { get; set; }
        [Required]
        [Range(5, 600, ErrorMessage = "Please enter correct value")]



        public double FineAmount { get; set; }
        [Required]
        [Range(5, 600, ErrorMessage = "Please enter valid day")]

        public int NoOfDays { get; set; }
    
        public virtual BookTable BookTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
