//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryproject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class library_management_systemEntities1 : DbContext
    {
        public library_management_systemEntities1()
            : base("name=library_management_systemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookFineTable> BookFineTables { get; set; }
        public virtual DbSet<BookReturnTable> BookReturnTables { get; set; }
        public virtual DbSet<BookTable> BookTables { get; set; }
        public virtual DbSet<BookTypeTable> BookTypeTables { get; set; }
        public virtual DbSet<DepartmentTable> DepartmentTables { get; set; }
        public virtual DbSet<IssueBookTable> IssueBookTables { get; set; }
        public virtual DbSet<StudentTable> StudentTables { get; set; }
        public virtual DbSet<StudentTypeTable> StudentTypeTables { get; set; }
        public virtual DbSet<login> logins { get; set; }
    }
}
